export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_ANSWERS = 'GET_ANSWERS';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_ANSWERS_SUCCESS = 'GET_ANSWERS_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';
export const SUBMIT_QUESTION = 'SUBMIT_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
